### ISSUE TITLE
Troubles with api fingerprint

### ISSUE THREAD

**Issue by Martin4Kansas** [CheckPointSW/cpAnsible#10]
I'm receiving the following error message when trying to run the demo playbook.
`fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Cannot operate on an unverified server. Please verify the server's fingerprint: '' and add it via the 'fingerprint' option of this module."}`
I have a fingerprint added though. I'm not sure why it's reading it as blank. Any support would be great.

**Comment by jordanmartinksu** [comment]
Solution was to delete the "fingerprints.txt" file and rerun.  This is a bug, though.

**Comment by jordanmartinksu** [comment]
Never mind, this worked once and now it fails again.  The fingerprints match and it still says unverified.

**Comment by jordanmartinksu** [comment]
The fingerprints.txt file exists and has the correct fingerprint for the ip address.

**Comment by jordanmartinksu** [comment]
Update: I got login to work by manually changing the port from 443 to 8443.  Unfortunately, you can't pass a port to login, so it always defaults to 443.  This problem persists when I try to add group, however.  I am not sure why.

**Comment by Martin4Kansas** [comment]
This problem only occurs for commands other than login because the wrong port, 443, is being used instead of our API port, 8443.  PR #13 addresses the issue by collecting the port from the url returned in the response and using it in subsequent commands.

**Comment by chkp-rdecker** [comment]
You are absolutely right.
Will review the suggested change request and fix the code.
Thank you.

**Comment by chkp-rdecker** [comment]
committed!
