### ISSUE TITLE
Read only?

### ISSUE THREAD

**Issue by starflighter** [CheckPointSW/cpAnsible#12]
Hi all,

just a question, is it possible to get only information?
To read the current rules and objects?

Can you show an example with ansible?

Thank you
starflighter

**Comment by chkp-rdecker** [comment]
Of course. You should use the "show-[NAME]" command, for example show-hosts, show-networks, show-access-rulebase, show-packages, or a generic show-objects.
Please refer to [Management API reference](https://sc1.checkpoint.com/documents/latest/APIs/index.html#web/show-objects~v1.2%20) for a full list of commands.

**Comment by starflighter** [comment]
Thank you for the explanation. :-)
