### ISSUE TITLE
Run-script fails as requested object is not found

### ISSUE THREAD

**Issue by Martin4Kansas** [CheckPointSW/cpAnsible#17]
Here is my playbook: 
---
- hosts: "localhost"
  vars_files:
  - r80_vars.yml
  tasks:  
  - name: "Login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
        port: 8443
        domain: System Data
      fingerprint: "{{mgmt_fingerprint}}"
    register: login_response

  - name: "Create output file"
    check_point_mgmt:
      command: run-script
      parameters:
        script-name: "Create output file"
        script: "touch output.txt"
        targets: "ztestintfw1"
      session-data: "{{login_response}}"

  - name: "Publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"

  - name: "Logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"

The response I get when using verbosity 3 is:

PLAY [localhost] ****************************************************************************************************************************
TASK [Gathering Facts] **********************************************************************************************************************ok: [127.0.0.1]

TASK [login] ********************************************************************************************************************************ok: [127.0.0.1]

TASK [Check Core Dumps] *********************************************************************************************************************fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Command 'run-script {u'script-name': u'List files', u'script': u'ls'}' failed with error message: Missing parameter: [targets]. All changes are discarded and the session is invalidated."}
        to retry, use: --limit @/mnt/c/Users/jm62602/Documents/CheckMates_Aug15_Demos/Ansible-R80-Scripts/GoldenImageScan.retry

PLAY RECAP **********************************************************************************************************************************127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1

TASK [Create output file] ***************************************************************************************************************************************************************************
task path: /mnt/c/Users/jm62602/Documents/CheckMates_Aug15_Demos/Ansible-R80-Scripts/GoldenImageScan.yml:18
Using module file /home/jordanmartin/lib/check_point_mgmt/check_point_mgmt.py
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: jordanmartin
<127.0.0.1> SSH: EXEC sshpass -d13 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/home/jordanmartin/.ansibl
e/cp/8239a62529 127.0.0.1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<127.0.0.1> (0, '/home/jordanmartin\n', '')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: jordanmartin
<127.0.0.1> SSH: EXEC sshpass -d13 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/home/jordanmartin/.ansibl
e/cp/8239a62529 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/jordanmartin/.ansible/tmp/ansible-tmp-1531938210.39-82269256870574 `" && echo ansible-tmp-1531938210.39-8226925687057
4="` echo /home/jordanmartin/.ansible/tmp/ansible-tmp-1531938210.39-82269256870574 `" ) && sleep 0'"'"''
<127.0.0.1> (0, 'ansible-tmp-1531938210.39-82269256870574=/home/jordanmartin/.ansible/tmp/ansible-tmp-1531938210.39-82269256870574\n', '')
<127.0.0.1> PUT /tmp/tmpGLVEwn TO /home/jordanmartin/.ansible/tmp/ansible-tmp-1531938210.39-82269256870574/check_point_mgmt.py
<127.0.0.1> SSH: EXEC sshpass -d13 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/hom
e/jordanmartin/.ansible/cp/8239a62529 '[127.0.0.1]'
<127.0.0.1> (0, 'sftp> put /tmp/tmpGLVEwn /home/jordanmartin/.ansible/tmp/ansible-tmp-1531938210.39-82269256870574/check_point_mgmt.py\n', '')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: jordanmartin
<127.0.0.1> SSH: EXEC sshpass -d13 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/home/jordanmartin/.ansibl
e/cp/8239a62529 127.0.0.1 '/bin/sh -c '"'"'chmod u+x /home/jordanmartin/.ansible/tmp/ansible-tmp-1531938210.39-82269256870574/ /home/jordanmartin/.ansible/tmp/ansible-tmp-1531938210.39-822692568705
74/check_point_mgmt.py && sleep 0'"'"''
<127.0.0.1> (0, '', '')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: jordanmartin
<127.0.0.1> SSH: EXEC sshpass -d13 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/home/jordanmartin/.ansibl
e/cp/8239a62529 -tt 127.0.0.1 '/bin/sh -c '"'"'/usr/bin/python /home/jordanmartin/.ansible/tmp/ansible-tmp-1531938210.39-82269256870574/check_point_mgmt.py; rm -rf "/home/jordanmartin/.ansible/tmp/
ansible-tmp-1531938210.39-82269256870574/" > /dev/null 2>&1 && sleep 0'"'"''
<127.0.0.1> (0, '\r\n{"msg": "Command \'run-script {u\'script-name\': u\'Create output file\', u\'targets\': u\'ztestintfw1\', u\'script\': u\'touch output.txt\'}\' failed with error message: Reque
sted object [ztestintfw1] not found. All changes are discarded and the session is invalidated.", "failed": true, "changed": false, "invocation": {"module_args": {"command": "run-script", "session-d
ata": "{\'changed\': False, \'response\': {\'url\': \'199.197.48.246:8443\', \'domain\': \'System Data\', \'fingerprint\': \'CF92395BEC6796E1E1E03DC079308AEFF2F3959B\', \'sid\': \'FDYOHwOl_cNuW6S_O
k14UWU6dJB9MCFzTKp0ei2At1A\'}}", "parameters": "{\'script-name\': \'Create output file\', \'targets\': \'ztestintfw1\', \'script\': \'touch output.txt\'}", "fingerprint": null}}}\r\n', 'Shared conn
ection to 127.0.0.1 closed.\r\n')
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "command": "run-script",
            "fingerprint": null,
            "parameters": "{'script-name': 'Create output file', 'targets': 'ztestintfw1', 'script': 'touch output.txt'}",
            "session-data": "{'changed': False, 'response': {'url': '199.197.48.246:8443', 'domain': 'System Data', 'fingerprint': 'CF92395BEC6796E1E1E03DC079308AEFF2F3959B', 'sid': 'FDYOHwOl_cNuW6
S_Ok14UWU6dJB9MCFzTKp0ei2At1A'}}"
        }
    },
    "msg": "Command 'run-script {u'script-name': u'Create output file', u'targets': u'ztestintfw1', u'script': u'touch output.txt'}' failed with error message: Requested object [ztestintfw1] not fo
und. All changes are discarded and the session is invalidated."
}
        to retry, use: --limit @/mnt/c/Users/jm62602/Documents/CheckMates_Aug15_Demos/Ansible-R80-Scripts/GoldenImageScan.retry

PLAY RECAP ******************************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1

It appears that "Requested object [ztestintfw1] not found." The problem is that this object a) exists and b) is found when making the same API call using Postman.  This issue has be thoroughly confused.  Any examples or insights would be greatly appreciated!

**Comment by chkp-rdecker** [comment]
you have to remove the "domain: System Data" parameter from the login command, as you should work in user data default domain, where the object "ztestintfw1" resides.
