### ISSUE TITLE
show-access-rulebase can't show more than 500 rules

### ISSUE THREAD

**Issue by bhupinderrandhawa27** [CheckPointSW/cpAnsible#18]
Currently show-access-rulebase can't show more than 500 rules. We would like to see all the rules in firewall and some of the firewalls we have has count close to 800 / 900. 

Because of current limitation of rest service show-access-rulebase 1-500 we can not read rules beyond 500.

Thanks
Bhupinder

**Comment by chkp-rdecker** [comment]
Are you using the limit of 500 as a parameter of your command?

**Comment by bhupinderrandhawa27** [comment]
Let me put in different way. For say we have total 950 rules in particular firewall , and when we try to fetch the rules it is only giving first 500 rules. When we put 1000 as a parameter command I am getting below error.

"code": "generic_err_invalid_parameter",
    "message": "Invalid parameter for [limit]. The invalid value [1000] should be replaced by one of the following values: [1-500]"
} 

So looks like max limit in API is set to 500 and if parameter is left blank then default is set to 50.

We need to extract all 950 rules from the firewall.

**Comment by bhupinderrandhawa27** [comment]
https://sc1.checkpoint.com/documents/latest/APIs/index.html#gui-cli/show-access-rulebase~v1.2%20

When I see the documentation, the limit parameter says below.
integer  Default: 50   Description: 1-500

**Comment by chkp-rdecker** [comment]
Got it.
You are correct - there is a bug in our Ansible code, will be fixed.
Thank you.

**Comment by bstlaurentnz** [comment]
Are there any plans to include the ability to specify an offset: parameter in the Ansible commands? Currently it's impossible to get more than the first 500 of any object in the DB (rules, hosts, networks, groups etc), or better yet, use the api_query command for show commands?

I'm having to write custom python scripts using the api and the api_query command?

**Comment by chkp-amiads** [comment]
@king88mob , there is a project coming up to be certified by RedHat, as part of it we will address this issue (this process will include additional changes).
I will check how much effort is it to fix this issue on our current version and will update if we will fix it now or only as part of the certification changes

**Comment by chkp-amiads** [comment]
Hi @king88mob , @bsr4mpune ,
We do support offset which can let you more than the first 500 rules, here is a task example:

 name: show access rulebase
      check_point_mgmt:
        command: show-access-rulebase
        parameters:
          name: "Network"
          limit: "500"
          **offset: "500"**

I'm closing this thread.
