### ISSUE TITLE
Fingerprint error when executing playbook

### ISSUE THREAD

**Issue by ddorseypromnetwork** [CheckPointSW/cpAnsible#19]
Greetings,

I've been playing with the module in hopes of leveraging this to add hosts to a group, but get the following message:

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command": "login",
            "fingerprint": "33:4B:04:AF:D8:85:20:F6:B0:75:28:ED:06:DE:C7:AB:67:65:18:5E",
            "parameters": "{'username': 'XXXXXX', 'management': 'XXXXXXXX', 'password': 'XXXXXXX'}",
            "session-data": null
        }
    }
}

MSG:

Cannot operate on an unverified server. Please verify the server's fingerprint: 'A0B10324AA4EB32B18F2FB2DEAF854433D5183B7' and add it via the 'fingerprint' option of this module.

I'm running this within a Vagrant machine against a management server in AWS if that makes a difference. My playbook is essentially the same as some of the examples provided:

---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: login
    check_point_mgmt:
      command: login
      parameters:
        username: "{{ cp_mgmt_admin_username }}"
        password: "{{ cp_mgmt_admin_password }}"
        management: "{{ cp_mgmt_public_ip }}"
      fingerprint: "{{ cp_mgmt_fingerprint }}"
    register: login_response

  - name: white listing host
    check_point_mgmt:
      command: add host
      parameters:
        name: "DD_Test_Host"
        ip-address: "192.168.1.1"
      session-data: "{{ login_response }}"

  - name: add host to group
    check_point_mgmt:
      command: add group
      parameters:
        name: "PIN_Group_Demo"
        members:
          - "DD_Test_Host"
      session-data: "{{ login_response }}"

  - name: publish changes
    check_point_mgmt:
      command: publish
      session-data: "{{ login_response }}"

  - name: install policy
    check_point_mgmt:
      command: install-policy
      parameters:
        policy-package: "Standard"
      session-data: "{{login_response}}"

Not sure why this would see the fingerprint for the management server change since I have confirmed that this is static. Each time it is ran this essentially comes back with a new fingerprint and halts the playbook.

I'm at a loss on how I can get this to work and any help is appreciated.

Thanks,
David

**Comment by chkp-rdecker** [comment]
Hi,
I have never seen that before.  Are you using a proxy or something else in-between the ansible server and the R80 mgmt server? Maybe something on your Vagrant VM configuration?

**Comment by chkp-amiads** [comment]
Hi @ddorseypromnetwork , im closing this issue as i don't see any reply for chkp-rdecker answer.
If you still have issues, please open new issue.
