### ISSUE TITLE
failed with error message: APIResponse received a response which is not a valid JSON

### ISSUE THREAD

**Issue by amabrouki** [CheckPointSW/cpAnsible#2]
Dear API Team,

I created  a simple ansible playbook to test it with Checkpoint.

But the playbook ends with the following error  : 

PLAY [localhost] **********************************************************************************************************************************************************************************************
TASK [Gathering Facts] ****************************************************************************************************************************************************************************************
ok: [127.0.0.1]
TASK [login] **************************************************************************************************************************************************************************************************
ok: [127.0.0.1]
TASK [add group] **********************************************************************************************************************************************************************************************
### fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Command 'add-group {u'name': u'group_demo'}' failed with error message: APIResponse received a response which is not a valid JSON.. All changes are discarded and the session is invalidated."}

PLAY RECAP ****************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1

##  This is my playbook : 

- hosts: "localhost"
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{mgmt_fingerprint}}"
    register: login_response

  - name: "add group"
    check_point_mgmt:
      command: add-group
      parameters:
        name: "group_demo"
      session-data: "{{ login_response }}"

Best regards.

**Comment by JonTheNiceGuy** [comment]
When I hit this issue, it turns out that Check Point's API is not idempotent, which means the *second* time you run it, you'll have the same issue. You'll need to go in and remove the group, then publish the change before you can test it again.

**Comment by amabrouki** [comment]
As you can see below, the group was not created. 

![image](https://user-images.githubusercontent.com/20537490/34781397-03a6e088-f626-11e7-9532-631a97bcae88.png)

**Comment by chkp-rdecker** [comment]
Hi,
This means that your login attempt probably failed.
Please verify that you have configured inside SmartConsole the API server's accessibility settings (Note no. 1 under Notes section).
Thanks.

**Comment by amabrouki** [comment]
Hi,

I created a new user with "API management Permission", and i have allowed all IPs to access to API.
I think now the connexion is OK.

But now i have the following error :
  **"msg": "Command 'add-group {u'name': u'group_demo'}' failed with error message: Management server failed to execute command. All changes are discarded and the session is invalidated."
}**

[error.txt](https://github.com/CheckPoint-APIs-Team/cpAnsible/files/1623011/error.txt)

Best regards.

**Comment by chkp-rdecker** [comment]
Hi,
Please run "api status -s [file-name]" command on the management server.
It produces a tar file in the current folder with all API log data.
Attach a file here for further analysis.
Thanks.

**Comment by amabrouki** [comment]
Hi,

The problem is solved, thank you.

I run "api status -s" and i verified "/opt/CPsuite-R80/fw1/log/api.elg". I found that the user has  "INSUFFICIENT_PERMISSIONS". 

FFICIENT_PERMISSIONS] errorFamily [Tried to create an object in an unauthorized folder bc137b06-3129-4885-a239-c2ce052586b8 from profile 62747182-8bae-43c1-9db8-1031b7db994f and object=com.checkpoint.objects.classes.dummy.CpmiNetworkObjectGroup CheckPointObject{metaInfo=com.checkpoint.management.dlecommon.ngm_api.MetaInfoForTopLevel@f3cba062, featuresPreset=2545b2a1-d128-3020-ae69-49fef9a0b448, features=[ce2be670-c260-11e4-8830-0800200c9a66, c1c7901a-9835-48cb-b434-31e8813b439d, 7f44117b-fa39-4ed0-be73-6c7e4c22d043, 5310cad7-e586-415a-be8a-830c96480adb, e682a9e6-bd8b-4faf-92ef-53dfd442e3bd], tags=[], systemTags=[1316ee9c-4f9c-49ca-85c0-37fbfa2f55ea, 1316ee9c-4f9c-49ca-85c0-37fbfa2f55eb, 26a8bdce-c8a7-4f73-8c76-5ec934d9205e, ea7f217a-3224-4bfc-9a21-8ab70e4478c3], actions=[], dynamicFeatures=null} {name='group_demo', objId='97edf971-7ac4-43fd-972b-281561f9f9b4', domain='41e821a0-3720-11e3-aa6e-0800200c9fde'}] message [An internal error has occurred.]
2018-01-12 10:04:11,608  WARN com.checkpoint.management.web_api.utils.WebApiCommandExceptionUtils.getErrorReply:52 [qtp-1926586040-36] - Unhandled GeneralRemoteFault error code [CP_ERR_INSUFFICIENT_PERMISSIONS]
2018-01-12 10:04:11,609 ERROR com.checkpoint.management.web_api.utils.WebApiCommandExceptionUtils.getErrorReply:219 [qtp-1926586040-36] -

Best regards.

**Comment by fyazzayf** [comment]
Hi,

I am having the same error. Can someone advise me what is the fix I should do?  Please advise!! :)

![capture](https://user-images.githubusercontent.com/37484288/47610577-d8a78780-da8a-11e8-834b-6f6959e696d6.PNG)


> Hi,
> Please run "api status -s [file-name]" command on the management server.
> It produces a tar file in the current folder with all API log data.
> Attach a file here for further analysis.
> Thanks.

**Comment by josekampos** [comment]
Hi. I'm having this exact same problem using the new 80.20 version.

fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Command 'show networks {u'limit': 50, u'details-level': u'standard', u'offset': 0}' failed ssage: APIResponse received a response which is not a valid JSON.. All changes are discarded and the session is invalidated."}

I think CheckPoint changed something in this latest version.

Please advise...

**Comment by chkp-amiads** [comment]
Hi @jordanmartinksu ,
Please run "api status -s [file-name]" command on the management server.
It produces a tar file in the current folder with all API log data.
Attach a file here for further analysis.

In addition, if you can share your playbook as well it will be good. 

Thanks.

**Comment by chkp-amiads** [comment]
Hi @josekampos ,
Please run "api status -s [file-name]" command on the management server.
It produces a tar file in the current folder with all API log data.
Attach a file here for further analysis.

In addition, if you can share your playbook as well it will be good.

Thanks.

**Comment by josekampos** [comment]
Hi, have attached the command output, plus additional data. Do take into consideration that i'm using versions 80.20 (it works on version 80.10).

Thank for the help

![output_error](https://user-images.githubusercontent.com/24719879/49010898-85e5ec00-f16c-11e8-8357-d5ca4b62e073.PNG)

[2018.11.26_11-03-05_api_data_debug.zip](https://github.com/CheckPointSW/cpAnsible/files/2615216/2018.11.26_11-03-05_api_data_debug.zip)


[1-demo-playbook.yml.txt](https://github.com/CheckPointSW/cpAnsible/files/2615220/1-demo-playbook.yml.txt)

**Comment by kabiter** [comment]
Hi. Pls to try this https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk119553

**Comment by chkp-amiads** [comment]
Hi @josekampos , your command should be like that **command: show-networks** (you're missing the '-' in the command).
In your playbook:

- name: show networks
      check_point_mgmt:
        **command: show networks**
        parameters: 
          limit: 50
          offset: 0
          details-level: "standard"
        session-data: '{{login_response}}'

when i changed it to:

- name: show networks
      check_point_mgmt:
        **command: show-networks**
        parameters: 
          limit: 50
          offset: 0
          details-level: "standard"
        session-data: '{{login_response}}'

It worked for me while running it against R80.20.

Please try to fix it in your playbook and let me know if issue was solved. 
(By the way, this exact playbook should fail for R80.10 as well....)

**Comment by josekampos** [comment]
Thanks for the support, and it seems that the issue is solved. I was using the mgmt_cli for testing, and the command is "show networks". It was runnning on my 80.10 because i had the correct playbook :). Thanks for the help

**Comment by gvo007** [comment]
I'm experiencing the same issue while using the tutorial-playbook.yml provided by CP:
`/workspace/ansible/cp# ansible-playbook tutorial-playbook.yml 
 [WARNING]: Found both group and host with same name: mso

 [WARNING]: Found both group and host with same name: apics


PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [login] ******************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [add host] ***************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Command 'add-host {u'name': u'host_demo', u'ip-address': u'1.2.3.5'}' failed with error message: Missing header: [X-chkp-sid]. All changes are discarded and the session is invalidated."}
        to retry, use: --limit @/root/workspace/ansible/cp/tutorial-playbook.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1
`

I also attached the output of the api status -s command
[2019.02.06_07-55-32_api_data.zip](https://github.com/CheckPointSW/cpAnsible/files/2835288/2019.02.06_07-55-32_api_data.zip)
