### ISSUE TITLE
Unable to run playbook

### ISSUE THREAD

**Issue by sajaltiwari** [CheckPointSW/cpAnsible#20]
Hi,
I am running a basic playbook against the Management Server but getting error of Authentication Failure even the credentials are correct and working fine, can someone help on how i can debug the issue and resolve it.

**Comment by sajaltiwari** [comment]
Getting below error if i do -vvvv

``
"msg": "Authentication failure., stderr output: OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/root/.ansible/cp/f569cf34ea\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to 127.0.0.1 [127.0.0.1] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 9994 ms remain after connect\r\ndebug1: permanently_set_uid: 0/0\r\ndebug1: identity file /root/.ssh/identity type -1\r\ndebug1: identity file /root/.ssh/identity-cert type -1\r\ndebug1: identity file /root/.ssh/id_rsa type -1\r\ndebug1: identity file /root/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /root/.ssh/id_dsa type -1\r\ndebug1: identity file /root/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /root/.ssh/id_ecdsa type -1\r\ndebug1: identity file /root/.ssh/id_ecdsa-cert type -1\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_5.3\r\ndebug1: match: OpenSSH_5.3 pat OpenSSH*\r\ndebug1: Enabling compatibility mode for protocol 2.0\r\ndebug1: Local version string SSH-2.0-OpenSSH_5.3\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: Wrote 864 bytes for a total of 885\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: kex_parse_kexinit: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1\r\ndebug2: kex_parse_kexinit: ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-rsa,ssh-dss\r\ndebug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se\r\ndebug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se\r\ndebug2: kex_parse_kexinit: hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96\r\ndebug2: kex_parse_kexinit: hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96\r\ndebug2: kex_parse_kexinit: zlib@openssh.com,zlib,none\r\ndebug2: kex_parse_kexinit: zlib@openssh.com,zlib,none\r\ndebug2: kex_parse_kexinit: \r\ndebug2: kex_parse_kexinit: \r\ndebug2: kex_parse_kexinit: first_kex_follows 0 \r\ndebug2: kex_parse_kexinit: reserved 0 \r\ndebug2: kex_parse_kexinit: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1\r\ndebug2: kex_parse_kexinit: ssh-rsa,ssh-dss\r\ndebug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se\r\ndebug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se\r\ndebug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96\r\ndebug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96\r\ndebug2: kex_parse_kexinit: none,zlib@openssh.com\r\ndebug2: kex_parse_kexinit: none,zlib@openssh.com\r\ndebug2: kex_parse_kexinit: \r\ndebug2: kex_parse_kexinit: \r\ndebug2: kex_parse_kexinit: first_kex_follows 0 \r\ndebug2: kex_parse_kexinit: reserved 0 \r\ndebug2: mac_setup: found hmac-sha1\r\ndebug1: kex: server->client aes128-ctr hmac-sha1 zlib@openssh.com\r\ndebug2: mac_setup: found hmac-sha1\r\ndebug1: kex: client->server aes128-ctr hmac-sha1 zlib@openssh.com\r\ndebug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<2048<8192) sent\r\ndebug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP\r\ndebug3: Wrote 24 bytes for a total of 909\r\ndebug2: dh_gen_key: priv key bits set: 161/320\r\ndebug2: bits set: 1068/2048\r\ndebug1: SSH2_MSG_KEX_DH_GEX_INIT sent\r\ndebug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY\r\ndebug3: Wrote 272 bytes for a total of 1181\r\ndebug3: check_host_in_hostfile: host 127.0.0.1 filename /root/.ssh/known_hosts\r\ndebug3: check_host_in_hostfile: host 127.0.0.1 filename /root/.ssh/known_hosts\r\ndebug3: check_host_in_hostfile: match line 3\r\ndebug1: Host '127.0.0.1' is known and matches the RSA host key.\r\ndebug1: Found key in /root/.ssh/known_hosts:3\r\ndebug2: bits set: 1006/2048\r\ndebug1: ssh_rsa_verify: signature correct\r\ndebug2: kex_derive_keys\r\ndebug2: set_newkeys: mode 1\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: Wrote 16 bytes for a total of 1197\r\ndebug2: set_newkeys: mode 0\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug1: SSH2_MSG_SERVICE_REQUEST sent\r\ndebug3: Wrote 52 bytes for a total of 1249\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug2: key: /root/.ssh/identity ((nil))\r\ndebug2: key: /root/.ssh/id_rsa ((nil))\r\ndebug2: key: /root/.ssh/id_dsa ((nil))\r\ndebug2: key: /root/.ssh/id_ecdsa ((nil))\r\ndebug3: Wrote 68 bytes for a total of 1317\r\ndebug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password\r\ndebug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic,password\r\ndebug3: preferred publickey,keyboard-interactive,password\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: keyboard-interactive,password\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Trying private key: /root/.ssh/identity\r\ndebug3: no such identity: /root/.ssh/identity\r\ndebug1: Trying private key: /root/.ssh/id_rsa\r\ndebug3: no such identity: /root/.ssh/id_rsa\r\ndebug1: Trying private key: /root/.ssh/id_dsa\r\ndebug3: no such identity: /root/.ssh/id_dsa\r\ndebug1: Trying private key: /root/.ssh/id_ecdsa\r\ndebug3: no such identity: /root/.ssh/id_ecdsa\r\ndebug2: we did not send a packet, disable method\r\ndebug3: authmethod_lookup password\r\ndebug3: remaining preferred: ,password\r\ndebug3: authmethod_is_enabled password\r\ndebug1: Next authentication method: password\r\ndebug3: packet_send2: adding 64 (len 60 padlen 4 extra_pad 64)\r\ndebug2: we sent a password packet, wait for reply\r\ndebug3: Wrote 148 bytes for a total of 1465\r\ndebug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password\r\nPermission denied, please try again.\r\ndebug3: packet_send2: adding 64 (len 51 padlen 13 extra_pad 64)\r\ndebug2: we sent a password packet, wait for reply\r\ndebug3: Wrote 148 bytes for a total of 1613\r\n",

``

**Comment by fhlmbrg** [comment]
@sajaltiwari are you trying to connect to localhost?

`debug1: Connecting to 127.0.0.1 [127.0.0.1] port 22.`

**Comment by sajaltiwari** [comment]
Hello,
I am trying to connect to the management server from the ansible server as mentioned in documents.
Providing my host file input here for more clarity, kindly let me know if i have mentioned anything wrong.



[localhost]
127.0.0.1
[localhost:vars]
ansible_user=[root]
ansible_ssh_pass=[root123]
ansible_python_interpreter=[/bin/python2.7]
#Optional (variables detailing the Check Point's management server access):
mgmt_server=[ip]

mgmt_user=[admin]

mgmt_password=[Apple123]

**Comment by fhlmbrg** [comment]
@sajaltiwari OK I see, have a look at the demo playbooks https://github.com/CheckPointSW/cpAnsible/blob/master/Playbooks/demo-playbook.yml#L9 .

There you specify the IP/FQDN of the mgmt server in the `login` task, then reference it in subsequent tasks using `session-data`.

Simplify while troubleshooting and hard-code the IP in the playbook, make that work, then you move parts out into inventory variables.

Adding to that, https://github.com/CheckPointSW/cpAnsible/blob/master/Playbooks/demo-playbook.yml#L1 is not necessary. Better to use an actual `hosts` entry and use `connection: local` in the play instead.

**Comment by sajaltiwari** [comment]
@holmahenkel I had masked the IP address in the above comment, please find below the host file entry and the playbook we are executing and getting the error.


[localhost]
127.0.0.1
[localhost:vars]
ansible_user=[root]
ansible_ssh_pass=[root123]
ansible_python_interpreter=[/bin/python2.7]
#Optional (variables detailing the Check Point's management server access):
mgmt_server=[10.76.6.188]
mgmt_user=[admin]
mgmt_password=[Apple123]
Playbook:

---
- hosts: 127.0.0.1                        
  tasks:

  - name: "login"                           
                                            
    check_point_mgmt:
      command: login
      parameters:
        username: "admin"           
        password: "Apple123"       
        management: "10.76.6.188"
      fingerprint: "9C:A9:D6:D9:8C:81:2D:EE:E0:02:36:D8:DB:17:B6:CF:6C:E8:B0:49"
    register: login_response

**Comment by sajaltiwari** [comment]
Hi,
The issue was resolved but now facing a different error, all the files are placed in the directories as mentioned in the documents but still it is saying files is missing.

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "module_stderr": "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 546\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_PWP_2n/ansible_module_check_point_mgmt.py\", line 8, in <module>\r\n    from cp_mgmt_api_python_sdk.lib import APIClient, APIClientArgs\r\nImportError: No module named cp_mgmt_api_python_sdk.lib\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}

**Comment by sajaltiwari** [comment]
Hi,
The issue was resolved but now facing a different error, all the files are placed in the directories as mentioned in the documents but still it is saying files is missing.

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "module_stderr": "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 546\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_PWP_2n/ansible_module_check_point_mgmt.py\", line 8, in <module>\r\n    from cp_mgmt_api_python_sdk.lib import APIClient, APIClientArgs\r\nImportError: No module named cp_mgmt_api_python_sdk.lib\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}

**Comment by fhlmbrg** [comment]
Hi @sajaltiwari,

Yeah this looks like you're missing the Python libraries / the system can't find the ones from Check Point.

Ref. the docs https://github.com/CheckPointSW/cpAnsible#installation-instructions , depending on platform, on MacOS the Check Point SDK library should be located in the folder `/Library/Python/2.7/site-packages/cp_mgmt_api_python_sdk`:

```
$ ls /Library/Python/2.7/site-packages/cp_mgmt_api_python_sdk
LICENSE   README.md   __init__.py   add_access_rule   clone_host   discard_sessions find_duplicate_ip lib
```

You can verify the Python libs location by running `$ ansible -m ping localhost -vvvv`, then look at one of the first lines of the output:
```
...
ansible python module location = /Library/Python/2.7/site-packages/ansible
...
```

Another way is checking if Python can import the module by doing this:
```
$ python
...
>>> import cp_mgmt_api_python_sdk                   <-- works
>>> import cp_mgmt_api_python_sdk_WRONG_NAME        <-- does not work
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cp_mgmt_api_python_sdk_WRONG_NAME
>>>
```

Fix that and you're up and running very soon :-)

**Comment by sajaltiwari** [comment]
Thanks @holmahenkel , it was because of the python modules missing in the required directory, i have 2 python and it was missing in the second one. the playbook can login to the checkpoint management server but it is failing to add the host and giving below error. I was using admin account to login but it is still giving me the same error, i have checked and all ip's are allowed in the API setting.

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command": "add-host",
            "fingerprint": null,
            "parameters": "{'name': 'host_demo', 'ip-address': '1.2.3.5'}",
            "session-data": "{'failed': False, 'changed': False, 'response': {'url': '10.76.6.188:443', 'domain': None, 'sid': None, 'fingerprint': '9CA9D6D98C812DEEE00236D8DB17B6CF6CE8B049'}}"
        }
    },
    "msg": "Command 'add-host {u'name': u'host_demo', u'ip-address': u'1.2.3.5'}' failed with error message: APIResponse received a response which is not a valid JSON.. All changes are discarded and the session is invalidated."
}

**Comment by sajaltiwari** [comment]
After multiple retries it is successful now but still it is not stable it fails some time and works some time, is there a way we can enable debug for this module to check why it fails sometimes.

**Comment by chkp-amiads** [comment]
Hi @sajaltiwari ,
Can you please specify what is "work sometime and fails some time"? If i get you right actions like add-host sometimes fails, am i right? if this is the case, i think it is better we can take it offline and we'll post answer here after it is solved. please send exact issue to amiads@checkpoint.com

Regards,
Amiad.

**Comment by sajaltiwari** [comment]
Hello Amiad,
Yes i have ran the tutorial script in my environment multiple times, some time it fails after login, sometime after adding host, sometimes after publish and sometime after logout. I will send you the screenshot on your email id.
