### ISSUE TITLE
Cant execute tutorial-playbook

### ISSUE THREAD

**Issue by fyazzayf** [CheckPointSW/cpAnsible#23]
Hi, I am getting the following issue when i tried to execute tutorial-playbook. Unsure what is the issue. Kindly hep.

[root@localhost Playbooks]# ansible-playbook demo-playbook.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/etc/ansible/cpAnsible/Playbooks/demo-playbook.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: login
      ^ here

**Comment by JonTheNiceGuy** [comment]
Hi @fyazzayf,

The issue here is that you don't have the module installed in a path that the playbook can use. This can either be that you've not moved the files to the paths suggested in the [readme](https://github.com/CheckPointSW/cpAnsible/blob/master/README.md) or that you've not configured the library path mentioned in the same file.

Good luck! :)

**Comment by fyazzayf** [comment]
> Hi @fyazzayf,
> 
> The issue here is that you don't have the module installed in a path that the playbook can use. This can either be that you've not moved the files to the paths suggested in the [readme](https://github.com/CheckPointSW/cpAnsible/blob/master/README.md) or that you've not configured the library path mentioned in the same file.
> 
> Good luck! :)

Hi Jon,

Thanks for the comment. Yes you are right, it was due to wrong path of the playbook. I am receiving the following error,

![capture](https://user-images.githubusercontent.com/37484288/47285499-babacc80-d61d-11e8-994f-268058265f35.PNG)

Any clue? Thanks in advance for your help Jon !! :)

**Comment by fyazzayf** [comment]
> Hi @fyazzayf,
> 
> The issue here is that you don't have the module installed in a path that the playbook can use. This can either be that you've not moved the files to the paths suggested in the [readme](https://github.com/CheckPointSW/cpAnsible/blob/master/README.md) or that you've not configured the library path mentioned in the same file.
> 
> Good luck! :)

Hi Jon,

Thanks for your response. Yes your are right, I realised that the path was wrong. It fixed the issue and helped me in executing the playbook. Below is the error popping out. Guess some API call issue.

![capture](https://user-images.githubusercontent.com/37484288/47289373-0628a700-d62d-11e8-8e7f-753d446d62bb.PNG)

Any clue? Thanks in advance for your help Jon!! :)

**Comment by JonTheNiceGuy** [comment]
There's an additional library that needs to be placed somewhere in your system.

In the README it shows this statement:

> 6. Move the `cp_mgmt_api_python_sdk` folder from the `check_point_mgmt` folder, into the Python packages folder: for example,  `/usr/lib/python2.7/site-packages` or `/usr/lib/python2.7/dist-packages`, depending on the Python installation (from-source or none-source built Python, respectively).

This is essentially where I think you have an issue. Hope this helps!

**Comment by chkp-amiads** [comment]
@fyazzayf, i saw you managed to run playbook on other issue you've opened, i'm closing this one.

@JonTheNiceGuy , thanks for your help.
