### ISSUE TITLE
command set-group failed with error message. “group_demo” could not be found 

### ISSUE THREAD

**Issue by fyazzayf** [CheckPointSW/cpAnsible#24]
Hi,

I am having the following error. Can someone advise me what is the fix I should do? Please advise!! :)

![capture](https://user-images.githubusercontent.com/37484288/47614856-965d6500-dae1-11e8-88cc-e346413c33a4.PNG)

**Comment by JonTheNiceGuy** [comment]
Sounds like you don't have a group called "group_demo" to add the host to? Perhaps you need to create the group first?
