### ISSUE TITLE
Booleans from Ansible (Python) to JSON Format

### ISSUE THREAD

**Issue by Senas23** [CheckPointSW/cpAnsible#26]
When Ansible produces a string for JSON data to be loaded, the module check_point_mgmt.py does not handle booleans with capitalized first letter as the value is being treated as python true boolean. In Python True and in JSON true. See the value mappings from/to Python/JSON.
Also, it seems like the Management API only takes all lowercase booleans.

**Comment by chkp-orso** [comment]
Thanks a lot, we fixed the issue and committed the changes here: https://github.com/CheckPointSW/cpAnsible/pull/27
And now we support Boolean parameters.
