### ISSUE TITLE
Parameter "groups": The error was: ValueError: Expecting , delimiter: line 

### ISSUE THREAD

**Issue by amabrouki** [CheckPointSW/cpAnsible#3]
Hello,

I have a problem with  the parameter "groups".
When i use it like in below code , the playbok ends with error :
But when i use it  with just the loop variable "{{item.memberof}}"  **groups: "{{item.memberof}}"**  , it ends without errors.

- name: "Modify groups"
  check_point_mgmt:
    command: set-group
    parameters:
      name: "{{obj.pre}}-{{item.name}}"
      **groups: "{{obj.pre}}-{{item.memberof}}"**
    session-data: "{{ login_response }}"
  with_items: "{{obj.obj_groups}}"

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Expecting , delimiter: line 1 column 52 (char 51)
failed: [localhost] (item={u'memberof': [u'test1'], u'name': u'wifi'}) => {"failed": true, "item": {"memberof": ["test2"], "name": "Wire"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_JBexb_/ansible_module_check_point_mgmt.py\", line 240, in <module>\n    main()\n  File \"/tmp/ansible_JBexb_/ansible_module_check_point_mgmt.py\", line 128, in main\n    parameters = json.loads(parameters.replace(\"'\", '\"'))\n  File \"/usr/local/lib/python2.7/json/__init__.py\", line 339, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/local/lib/python2.7/json/decoder.py\", line 364, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/local/lib/python2.7/json/decoder.py\", line 380, in raw_decode\n    obj, end = self.scan_once(s, idx)\nValueError: Expecting , delimiter: line 1 column 52 (char 51)\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

**Comment by chkp-rdecker** [comment]
Hi,
There is no such parameter "groups" in [set-group] command. It should be "members".
Please refer to example playbooks.
BTW, the error is about invalid JSON load...

**Comment by amabrouki** [comment]
Hello,

I have checked the API Reference documentation, and as you can see bellow, the parameter  "groups" is in  [set-group] command.

![image](https://user-images.githubusercontent.com/20537490/35505346-285f27e0-04e6-11e8-8ff5-435e80e0ae0d.png)

**Comment by chkp-rdecker** [comment]
Ok, now I understand what you are trying to do - you want to add your group object to other groups, to setup a recursive structure.
In this case, this should be identical to the syntax you used for adding members to the group.

**Comment by chkp-rdecker** [comment]
Hi, have you solved the issue?

**Comment by amabrouki** [comment]
Hi,
Yes, but i still don't know why i can't use two variables with the parameter "groups".
Because, i have the same problem with add-host and add-network commands.

**Comment by chkp-rdecker** [comment]
Does this work with the parameter "members" as you expect it to work?

**Comment by amabrouki** [comment]
Hi,  
Yes, i applyed Set-group command with  parameter "members" to the parent group.
