### ISSUE TITLE
run-script with multiple tragets

### ISSUE THREAD

**Issue by sinu** [CheckPointSW/cpAnsible#31]
Hello Team,

I am trying to run run-script with multiple target firewalls, is this possible if so how we can add the variable values?

**Comment by chkp-orso** [comment]
Hi,

Its similar to any parameter of type "list".

We have documentation of our API commands, and here is a link to the documentation of the run-script command: https://sc1.checkpoint.com/documents/latest/APIs/index.html?#web/run-script~v1.4%20

And also I wrote an example playbook to demonstrate run-script with multiple targets (you just need to insert the fingerprint of your machine).

[run-script.zip](https://github.com/CheckPointSW/cpAnsible/files/3125155/run-script.zip)

Thanks

**Comment by sinu** [comment]
thanks for the update, i figured out the same and i am able to execute form tower
