### ISSUE TITLE
Cannot operate on an unverified server. Please verify the server's fingerprint: '' and add it via the 'fingerprint' option of this module

### ISSUE THREAD

**Issue by abhishah-03** [CheckPointSW/cpAnsible#32]
Hi Guys ,

I am getting the unverified server error . I have added the "api fingerprint" SHA1 in the code ; followed all the steps as mentioned in the Readme file and webapi docs ; still not able to identify what could be wrong .  Can anyone please suggest  ??

The CP api is listening on port - 443 ; can see the logs of the playbook hitting checkpoint manager on 443 , added the fingerprint in the playbook .  But still the playbook complains of unverified server error .

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": null,
            "command": "login",
            "context": "web_api",
            "fingerprint": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "parameters": "{'username': 'XXXX', 'management': 'XXXXX', 'password': '@@@##$'}",
            "session-data": null
        }
    },
    "msg": "Cannot operate on an unverified server. Please verify the server's fingerprint: '' and add it via the 'fingerprint' option of this module."
}
        to retry, use: --limit @/home/AA-ANSIBLE001/my_script.retry

**Comment by chkp-orso** [comment]
Hi,
In the folder of your playbook, do you have file called "fingerprints.txt"? 
If so, try to delete the file and run the playbook again please

Waiting for updates :)

**Comment by abhishah-03** [comment]
Thanks for the quick update , but still with deleting the file (fingerprints.txt) , no luck ... 

**Same error **
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Cannot operate on an unverified server. Please verify the server's fingerprint: '' and add it via the 'fingerprint' option of this module."}


Also , What I understand using the cpAnsible module - it makes a self-ssh on localhost (127.0.0.1) and then from this it calls the python module - cp  which creates the API calls (443) to connect with the checkpoint management IP .

Is there a way I can remove the self-**ssh** logic to run this cpAnsible because from on the ansible machine from where I am running this needs a --key-file as well for ssh access .

**Comment by chkp-orso** [comment]
NP
Can you send me please your "hosts" file, and the playbook you are trying to run

**Comment by abhishah-03** [comment]
Playbook is pretty simple -

---
- hosts: "localhost"
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "BD:13:8E:82:8F:72:C0:2B:51:B0:E3:3C:FE:DE:2B:55:0D:CB:51:02"
    register: login_response

  - name: "add host"
    check_point_mgmt:
      command: add-host
      parameters:
        name: "host_demo"
        ip-address: "1.2.3.5"
      session-data: "{{ login_response }}"

  - name: "add group"
    check_point_mgmt:
      command: add-group
      parameters:
        name: "group_demo"
        members:
          - "host_demo"
      session-data: "{{ login_response }}"

  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"


*************

hosts file -

#cpAnsible

[localhost]
127.0.0.1
[localhost:vars]
ansible_user=ANSIBLE_user
ansible_ssh_pass=xxxxxxxxx
#ansible_python_interpreter=/usr/lib/python2.7/site-packages/ansible
# Optional (variables detailing the Check Point's management server access):
mgmt_server=10.x.x.x
mgmt_user=xxxxx
mgmt_password=xxxxx!!!

**********************

Updated the module path -
in /etc/ansible/ansible.cfg

library        = /usr/share/my_modules/

*****************

**Comment by chkp-orso** [comment]
I suggest we do a remote session. When are you available for this?

**Comment by abhishah-03** [comment]
Sure,  thay will be great.  I am available from 9am to 3pm IST any day...

**Comment by chkp-orso** [comment]
Great, can we do it tomorrow(23.5.19) at 13:30 IST time?

**Comment by chkp-orso** [comment]
I can do it any day at 13:30 IST time, so please tell me when you are available :)

**Comment by chkp-orso** [comment]
Ok I'm closing this issue. Please feel free to send me a message here

**Comment by LucaTino** [comment]
Hello, I've the same problem, what was the solution?

**Comment by chkp-orso** [comment]
Hi,
In the folder of your playbook, do you have file called "fingerprints.txt"?
If so, try to delete the file and run the playbook again please

Waiting for updates :)
