### ISSUE TITLE
Python version requirements

### ISSUE THREAD

**Issue by eperegudov** [CheckPointSW/cpAnsible#33]
Hi!

README contains the requirement:

> 4. Install a Python interpreter with version >= 2.7.9, but not Python 3 or above.

I'm trying to operate with cpAnsible module from virtualenv with Python 3.5.2 and at first glance it works correct. Is there any obvious or hidden reasons to do not use Python 3 with cpAnsible module?

**Comment by chkp-orso** [comment]
If it works, great, but we don't support it. Anyway we develop a new module for ansible which support any python version.
The EST is end of Q3. 
Hopefully you will find it useful.
