### ISSUE TITLE
Unable to Run Playbook - error - ImportError: No module named cpapi

### ISSUE THREAD

**Issue by ankda18** [CheckPointSW/cpAnsible#35]
Hi all,

I facing error when integrating Ansible with checkpoint Management Server. I followed Ansible deployment guide. I get below error when running playbook.

ankur@ankur-virtual-machine:~/71442b35e6e8d830e19f776a7b1b6cc8$ ansible-playbook ansible-cp-test.yml

PLAY [GW] ******************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [login] ***************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ankur/.ansible/tmp/ansible-tmp-1561291034.04-84766382214963/AnsiballZ_check_point_mgmt.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ankur/.ansible/tmp/ansible-tmp-1561291034.04-84766382214963/AnsiballZ_check_point_mgmt.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ankur/.ansible/tmp/ansible-tmp-1561291034.04-84766382214963/AnsiballZ_check_point_mgmt.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_check_point_mgmt_payload_Z3CJEO/__main__.py\", line 8, in <module>\r\nImportError: No module named cpapi\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

I already copied cp_mgmt_api_python_sdk in path and imported it as well through python interpreter. 

Below is the host file:

## db-[99:101]-node.example.com
[GW]
127.0.0.1
[GW:vars]
ansible_user=ankur
mgmt_server=192.168.155.20
appliance_name=GW
ansible_python_interpreter=/usr/bin/python2.7
mgmt_user=admin
mgmt_password=vpn123
fingerprint=70:7C:35:40:15:8E:78:0A:A8:64:76:23:3C:1D:46:E5:6B:ED:E2:EA

Kindly help.

**Comment by chkp-amiads** [comment]
Hi @ankda18 ,
From the error it looks like you have issue with import of cpapi nodule.

Have you followed the instructions for using our SDK as written in this section '**SDK usage from a remote machine**' (https://github.com/CheckPointSW/cp_mgmt_api_python_sdk)?

Please use 'pip' to install our SDK as written there (since Ansible is a remote machine) and let me know if it solved it.

Regards,
Amiad.
