### ISSUE TITLE
Ansible to checkpoint No module named cpapi\n" "msg": "MODULE FAILURE!

### ISSUE THREAD

**Issue by satishmantri** [CheckPointSW/cpAnsible#38]
Ansible to checkpoint wih R80.10 and ansible HFA and i am having issues  using https://github.com/CheckPointSw/cpAnsible 
using the example from there with out using the hosts file...

ansible --version
ansible 2.9.3
  config file = /root/xxxxx/ansible.cfg
  configured module search path = [u'/etc/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
 
Example playbook
---
- hosts: "localhost"                        # Note #2 in the Description section
  tasks:
  - name: "login"                           # You have to login to the management
                                            # server before running any commands
    check_point_mgmt:
      command: login
      parameters:
        username: "{{z}"           # Variables set in /etc/ansible/hosts, to avoid needing
        password: "{{y}}"       # to type your login details in every playbook.
        management: "{{x}}"
      fingerprint: "xx"
    register: login_response                # Register the output from the login
                                            # command so we can use it later to run commands.
  - name: "add host"
    check_point_mgmt:
      command: add-host                     # Name of the command
      parameters:                           #  The parameters for it, in dictionary form
        name: "host_demo"
        ip-address: "1.2.3.5"
      session-data: "{{ login_response }}"  # The session data we received from
                                            # the login command is used here to run 'add-host'
  - name: "add group"
    check_point_mgmt:
      command: add-group
      parameters:
        name: "group_demo"
        members:
          - "host_demo"
      session-data: "{{ login_response }}"
  - name: "publish"                         # Publishing is important if you want
                                            # your changes to be saved.
    check_point_mgmt:                       # This will actually 'discard' when
                                            # check mode is enabled (ansible-playbook -C)
                                            # unless you add 'always_run: yes' to the task.
      command: publish
      session-data: "{{login_response}}"
 
Error
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1582234960.1-32781520738983/AnsiballZ_che                                                                                                                                                               ck_point_mgmt.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1582234960.1-32781520738983/AnsiballZ_che                                                                                                                                                               ck_point_mgmt.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1582234960.1-32781520738983/AnsiballZ_che                                                                                                                                                               ck_point_mgmt.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.check_point_mgmt', init_globals=N                                                                                                                                                               one, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_check_point_mgmt_payload_Uz8c7z/ansible_check_point_mgmt_pa                                                                                                                                                               yload.zip/ansible/modules/check_point_mgmt.py", line 8, in <module>
ImportError: No module named cpapi

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansibl                                                                                                                                                               e/tmp/ansible-tmp-1582234960.1-32781520738983/AnsiballZ_check_point_mgmt.py\", l                                                                                                                                                               ine 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible                                                                                                                                                               -tmp-1582234960.1-32781520738983/AnsiballZ_check_point_mgmt.py\", line 94, in _a                                                                                                                                                               nsiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  Fil                                                                                                                                                               e \"/root/.ansible/tmp/ansible-tmp-1582234960.1-32781520738983/AnsiballZ_check_p                                                                                                                                                               oint_mgmt.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansibl                                                                                                                                                               e.modules.check_point_mgmt', init_globals=None, run_name='__main__', alter_sys=T                                                                                                                                                               rue)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fna                                                                                                                                                               me, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _ru                                                                                                                                                               n_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib                                                                                                                                                               64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n                                                                                                                                                                 File \"/tmp/ansible_check_point_mgmt_payload_Uz8c7z/ansible_check_point_mgmt_pay                                                                                                                                                               load.zip/ansible/modules/check_point_mgmt.py\", line 8, in <module>\nImportError                                                                                                                                                               : No module named cpapi\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    s                                                                                                                                                               kipped=0    rescued=0    ignored=0

**Comment by satishmantri** [comment]
show installer packages
**  ************************************************************************* **
**              Connection error. Packages list might be incomplete           **
**  ************************************************************************* **
**  ************************************************************************* **
**                                 Hotfixes                                   **
**  ************************************************************************* **
Display name                                      Status
Check_Point_R80.10_JHF_T245_Ansible_Hotfix_sk1
   14661_FULL.tgz                                 Installed
Check_Point_R80_10_JUMBO_HF_Bundle_T245_FULL.t
   gz                                             Installed
HOTFIX_R80_10                                     Installed (Legacy)

**Comment by chkp-orso** [comment]
Hi :)

This repository is deprecated and unsupported.
Also I don't recognize the error. 
Please move to the official Ansible-Check Point integration in: [https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection](https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection)
If you run into problems please reach us out.

Thanks, Or

**Comment by satishmantri** [comment]
appreciate you reaching out to me, will work on it accordingly
Thanks & Regards,
Satish Mantri

Cell : 301 800 1845

**Comment by chkp-orso** [comment]
Thanks!
