### ISSUE TITLE
Possible other path for python_sdks

### ISSUE THREAD

**Issue by ghost** [CheckPointSW/cpAnsible#4]
6. Move the cp_mgmt_api_python_sdk directory from the check_point_mgmt directory, into **/usr/lib/python2.7/site-packages**

Depending on the python install, the python's packages folder could also be at:
/usr/lib/python2.7/dist-packages

Could be worth adding into your doc.
Ref: https://leemendelowitz.github.io/blog/how-does-python-find-packages.html

**Comment by chkp-rdecker** [comment]
Hi,
Thank you for pointing us to this information.
We'll definitely add this to our doc.

**Comment by chkp-rdecker** [comment]
Done.
