### ISSUE TITLE
Session-timeout parameter not working (proposed fix included)

### ISSUE THREAD

**Issue by ghost** [CheckPointSW/cpAnsible#6]
During the **login** step, the `Session-timeout` parameter is not applied. The login commands gets into a specific conditionnal, and a bunch of parameters available in the mgmt_cli or others are simpliy not added in this call.

**Proposed fix**

In check_point_mgmt.py, main():, look for the **timeout ** and **payload ** sections
```
def main():
    global was_changed
    # Initializing parameters to variables:
    command = module.params["command"]
    parameters = module.params.get("parameters")
    session_data = module.params.get("session-data")
    fingerprint = module.params.get("fingerprint")
    if parameters:
        parameters = json.loads(parameters.replace("'", '"'))
    if command == "login":
        # Login parameters:
        username = parameters.get("user", parameters.get("username"))
        password = parameters.get("pass", parameters.get("password"))
        management = parameters.get("management", "127.0.0.1")
        port = parameters.get("port", 443)
        domain = parameters.get("domain")
        timeout = parameters.get("session-timeout", 600)
        payload = {"session-timeout": timeout}
        client_args = APIClientArgs(server=management, port=port)
        client = APIClient(client_args)
        # Validate fingerprint:
        validate_fingerprint(client, fingerprint)
        # Tries to login:
        login_res = client.login(username=username, password=password, domain=domain, payload=payload)
```

A double check for the other login parameters available should be done, or something more general to make sure the login function always use every parameter available.

**Comment by chkp-rdecker** [comment]
Thank you for this input.
We will verify and fix as needed and inform you when published.

**Comment by chkp-rdecker** [comment]
"session-timeout" parameter parsing is added for the login command.
no further parameters are required for Ansible module functionality.
the "read-only" parameter is "false" by default.
thank you!
