### ISSUE TITLE
Idempotence/Skip over errors

### ISSUE THREAD

**Issue by MLC-Mat** [CheckPointSW/cpAnsible#7]
A common requirement for Anisble implementations is the ability to run many times and get the same result... e.g. If creating a file that is already there in the desired state, ansible skips to the next step.]

The cpAnsible library doesnt follow this pattern. For example if I run a playbook to create Checkpoint object, then run it again, it will fail the second time (and also seems to invalidate the session).

Are there any tips for ensuring the runs are re-runnable? Even skipping on to the next step would be useful. I tried the standard ansible option of  ignore_errors: yes.... but the next API call is bounced as the session is invalid post error. Any suggestions?

**Comment by chkp-rdecker** [comment]
This is correct, cpAnsible library doesn't follow the pattern mentioned, because it is **stateless**.
We will check to see what can be done.

**Comment by JonTheNiceGuy** [comment]
Ideally, the library would perform Create and Update actions like this:

1. Create a new session. (State: "OK")
1. Check whether the resource exists. If not, create the resource (State: "Changed")
2. Check whether the resource's properties are set as desired. If not, set the properties (State "Changed")
3. If the state has changed, commit the changes. If the commit does not apply, State: "failed". If not, discard the session.

Delete actions should be like this:
1. (State: "OK")
1. Check whether the resource exists. If it does, create a session, delete the resource and commit it. (State: "Changed"). If the delete action fails abort (State: "Failed")

**Comment by Martin4Kansas** [comment]
[This ](https://i.imgur.com/ViQC8hr.png)is a bit of a rudimentary solution that doesn't have all of the logic that it should, but it's what I use to avoid these errors.  Best of luck to you, @JonTheNiceGuy and @MLC-Mat.

**Comment by MLC-Mat** [comment]
Thanks @jordanmartinksu . Yes doesnt look to cover every scenario, but very useful none the less

**Comment by fhlmbrg** [comment]
@chkp-rdecker ref. what @MLC-Mat and @JonTheNiceGuy are saying, do you have any background into why the module doesn't support idempotency?

Due to this fact we currently have to do our own checks inline in the playbook to determine if objects exist or not, before we do anything.

I'm also aware of the `set-if-exists` parameter, which could have solved it(?), but that's not supported by all API calls, ref. https://sc1.checkpoint.com/documents/latest/APIs/index.html?#cli/add-host~v1.2 (supported) vs. https://sc1.checkpoint.com/documents/latest/APIs/index.html?#cli/add-trusted-client~v1.2 (not supported).

IMO it would be a lot cleaner if this all was handled by the module itself.

**Comment by chkp-rdecker** [comment]
Hi Fredrik,
We are aware of this limitation and are working on a resolution.
Thank you.

**Comment by fhlmbrg** [comment]
@chkp-rdecker thanks for the reply, excellent :-)

**Comment by MLC-Mat** [comment]
Awesome- thanks guys. This will be a big win for us. Essentially allowing things like rules to be easily managed in CI/CD rather than old fashioned spreadsheet based approvals

**Comment by MLC-Mat** [comment]
Has there been any movement on this one at all please?

Thanks a lot

Mat

**Comment by chkp-amiads** [comment]
Hi @MLC-Mat , we are working on our Ansible module to be certified (working with RedHat team), as part of this effort we will address idempotence issue. We are in the early stages of re-design. 
When we will have new solution, it will be uploaded to Check Point github account and will be part of Ansible certified modules.

**Comment by marccan** [comment]
Hi do you have any ETA for this new version of the module ?

**Comment by chkp-amiads** [comment]
Hi @marccan , as part of our 2019 developments, we’re working on a newer version of Ansible module that will be included as part of Ansible module index and will support (among all) idempotency.

**Comment by marccan** [comment]
Hi, is there any news about this new version ?
Any estimated ETA?

**Comment by chkp-amiads** [comment]
Our target is to release it during 2019. No final ETA. We are aware of the need and doing our best, working in full cooperation with RedHat teams to release it as soon as we can.

**Comment by padavrexi** [comment]
Hi,I suppose that future development will be focused primarily (exclusively?) on the official Ansible modules, correct?
