### ISSUE TITLE
Uses Outside the API

### ISSUE THREAD

**Issue by Martin4Kansas** [CheckPointSW/cpAnsible#8]
I'm curious if the CheckPoint folks have written any example playbooks that SSH directly into the Checkpoint Management Device so as to avoid the limitations of the rather small API library and Python SDK.  I feel that there are a lot of uses that extend outside of those realms.

**Comment by JonTheNiceGuy** [comment]
The problem with SSH'ing into the appliance is that there aren't all the Python packages you need on the box, which means you're limited to running RAW commands.

**Comment by chkp-rdecker** [comment]
Hi,
I'm not aware of such example playbooks. Our Ansible module runs against our Management Server, not against a target device. To execute operation on a target device, you can use our "run-script" API command - 
[run-script](https://sc1.checkpoint.com/documents/latest/APIs/index.html#gui-cli/run-script~v1.2%20)
Hope this helps.
